name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     build: npm run e2e
          # start: npm run e2e
          # por el momento no funciona
      - name: build
      - run: |
        npm install
        npm run e2e
        